
API Logic Project Server Setup (01JP732DJNM0EKQXAF2KA7VKKB) Starting with CLI args: 
.. api_logic_server_run.py

Created August 03, 2024 09:34:01 at /opt/projects/by-ulid/01JP732DJNM0EKQXAF2KA7VKKB

Data Model Loaded, customizing...
..discovered models: []
LogicBank Activation - declare_logic.py
Loading rules from /opt/projects/by-ulid/01JP732DJNM0EKQXAF2KA7VKKB/logic/wg_rules
01JP733V268CKQNJPD728B8Y5H rule file: logic/wg_rules/Customer_Balance_Rule.py
01JP733V29MY8WSZVNH7XA1MJT rule file: logic/wg_rules/Customer_Balance_Sum_Rule.py
01JP733V2AA51Q598FT9NNAMDN rule file: logic/wg_rules/Order_Amount_Total_Sum_Rule.py
01JP733V2BMD1W3QZX4RZ92QX1 rule file: logic/wg_rules/Item_Amount_Formula_Rule.py
01JP733V2CZX51BKNT6FHPF0N8 rule file: logic/wg_rules/Item_Unit_Price_Copy_Rule.py
01JP732EZV7MB5EW8X45B6X8FE rule file: logic/wg_rules/Customer_Balance_Constraint.py
01JP732F0AF6ECED61ENW0PT21 rule file: logic/wg_rules/Order_Kafka_Integration.py
01JP732F0D701XE32B8SJNE0JR rule file: logic/wg_rules/Customer_Name_Constraint.py
01JP732F0GBQ2A9KWHVX5AGQNK rule file: logic/wg_rules/Customer_Name_Constraint.py
[32mLoading Rule Module Customer_Balance_Rule 01JP733V268CKQNJPD728B8Y5H [0m
[32mLoading Rule Module Customer_Balance_Sum_Rule 01JP733V29MY8WSZVNH7XA1MJT [0m
[32mLoading Rule Module Order_Amount_Total_Sum_Rule 01JP733V2AA51Q598FT9NNAMDN [0m
[32mLoading Rule Module Item_Amount_Formula_Rule 01JP733V2BMD1W3QZX4RZ92QX1 [0m
[32mLoading Rule Module Item_Unit_Price_Copy_Rule 01JP733V2CZX51BKNT6FHPF0N8 [0m
[32mLoading Rule Module Customer_Balance_Constraint 01JP732EZV7MB5EW8X45B6X8FE [0m
[32mLoading Rule Module Order_Kafka_Integration 01JP732F0AF6ECED61ENW0PT21 [0m
[32mLoading Rule Module Customer_Name_Constraint 01JP732F0D701XE32B8SJNE0JR [0m
[32mLoading Rule Module Customer_Name_Constraint 01JP732F0GBQ2A9KWHVX5AGQNK [0m

The following rules have been loaded
Rule Bank[0xffffaa0f9cd0] (loaded 2025-03-13 06:29:54.538632)
Mapped Class[Customer] rules:
  Constraint Function: None 
  Derive <class 'database.models.Customer'>.balance as Sum(Order.amount_total Where Rule.sum(derive=Customer.balance, as_sum_of=Order.amount_total, where=lambda row: row.date_shipped is None) - <function init_rule.<locals>.<lambda> at 0xffffa9e168e0>)
  Constraint Function: None 
  Constraint Function: None 
  Constraint Function: None 
Mapped Class[Order] rules:
  Derive <class 'database.models.Order'>.amount_total as Sum(Item.amount Where  - None)
  RowEvent Order.send_row_to_kafka() 
Mapped Class[Item] rules:
  Derive <class 'database.models.Item'>.amount as Formula (-1): Rule.formula(derive=Item.amount, as_expression=la [...]
  Derive <class 'database.models.Item'>.unit_price as Copy(product.unit_price)

The following attributes have been referenced

..Customer.balance: constraint
..Customer.credit_limit: constraint
..Customer.balance: aggregate derivation
..Order.date_shipped: aggregate where clause
..Order.amount_total: sum derived from
..Customer.balance: constraint
..Customer.credit_limit: constraint
..Customer.name: constraint
..Customer.name: constraint
..Order.amount_total: aggregate derivation
..Item.amount: sum derived from
..Item.quantity: - formula
..Item.unit_price: - formula
..Item.unit_price: parent copy derivation
..Product.unit_price: parent copy from

The following rules have been activated
Rule Bank[0xffffaa0f9cd0] (loaded 2025-03-13 06:29:54.538632)
Mapped Class[Customer] rules:
  Constraint Function: None 
  Derive <class 'database.models.Customer'>.balance as Sum(Order.amount_total Where Rule.sum(derive=Customer.balance, as_sum_of=Order.amount_total, where=lambda row: row.date_shipped is None) - <function init_rule.<locals>.<lambda> at 0xffffa9e168e0>)
  Constraint Function: None 
  Constraint Function: None 
  Constraint Function: None 
Mapped Class[Order] rules:
  Derive <class 'database.models.Order'>.amount_total as Sum(Item.amount Where  - None)
  RowEvent Order.send_row_to_kafka() 
Mapped Class[Item] rules:
  Derive <class 'database.models.Item'>.amount as Formula (1): Rule.formula(derive=Item.amount, as_expression=la [...]
  Derive <class 'database.models.Item'>.unit_price as Copy(product.unit_price)
Logic Bank 01.20.26 - 13 rules loaded
Exposing /Customer
Exposing /Item
Exposing /Order
Exposing /OrderDetail
Exposing /Product
Declare   API - api/expose_api_models, endpoint for each table on localhost:8282, customizing...
..discovered services: ['ontimize_api.py', 'system.py', 'new_service.py', 'newer_service.py']
Kafka Consumer not activated

API Logic Project loaded (not WSGI), version: 14.03.15
.. startup message: normal start
 (running from docker container at flask_host: 0.0.0.0 - may require refresh)

API Logic Project (name: 01JP732DJNM0EKQXAF2KA7VKKB) starting:
..Explore data and API at http_scheme://swagger_host:port http://localhost:6004   *
.... with flask_host: 0.0.0.0
.... and  swagger_port: 8282

Alert: These following are **Critical** to unlocking value for project: 01JP732DJNM0EKQXAF2KA7VKKB:
.. see logic.declare_logic.py       -- 
.. see security.declare_security.py -- ALERT:  *** Security Not Enabled ***


*************************************************************************
*   Startup Instructions: Open your Browser at: http://localhost:6004   *
*************************************************************************

 * Serving Flask app 'API Logic Server'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:6004
 * Running on http://172.17.0.2:6004
[33mPress CTRL+C to quit[0m
 * Restarting with stat

API Logic Project Server Setup (01JP732DJNM0EKQXAF2KA7VKKB) Starting with CLI args: 
.. api_logic_server_run.py

Created August 03, 2024 09:34:01 at /opt/projects/by-ulid/01JP732DJNM0EKQXAF2KA7VKKB

Data Model Loaded, customizing...
..discovered models: []
LogicBank Activation - declare_logic.py
Loading rules from /opt/projects/by-ulid/01JP732DJNM0EKQXAF2KA7VKKB/logic/wg_rules
01JP733V268CKQNJPD728B8Y5H rule file: logic/wg_rules/Customer_Balance_Rule.py
01JP733V29MY8WSZVNH7XA1MJT rule file: logic/wg_rules/Customer_Balance_Sum_Rule.py
01JP733V2AA51Q598FT9NNAMDN rule file: logic/wg_rules/Order_Amount_Total_Sum_Rule.py
01JP733V2BMD1W3QZX4RZ92QX1 rule file: logic/wg_rules/Item_Amount_Formula_Rule.py
01JP733V2CZX51BKNT6FHPF0N8 rule file: logic/wg_rules/Item_Unit_Price_Copy_Rule.py
01JP732EZV7MB5EW8X45B6X8FE rule file: logic/wg_rules/Customer_Balance_Constraint.py
01JP732F0AF6ECED61ENW0PT21 rule file: logic/wg_rules/Order_Kafka_Integration.py
01JP732F0D701XE32B8SJNE0JR rule file: logic/wg_rules/Customer_Name_Constraint.py
01JP732F0GBQ2A9KWHVX5AGQNK rule file: logic/wg_rules/Customer_Name_Constraint.py
[32mLoading Rule Module Customer_Balance_Rule 01JP733V268CKQNJPD728B8Y5H [0m
[32mLoading Rule Module Customer_Balance_Sum_Rule 01JP733V29MY8WSZVNH7XA1MJT [0m
[32mLoading Rule Module Order_Amount_Total_Sum_Rule 01JP733V2AA51Q598FT9NNAMDN [0m
[32mLoading Rule Module Item_Amount_Formula_Rule 01JP733V2BMD1W3QZX4RZ92QX1 [0m
[32mLoading Rule Module Item_Unit_Price_Copy_Rule 01JP733V2CZX51BKNT6FHPF0N8 [0m
[32mLoading Rule Module Customer_Balance_Constraint 01JP732EZV7MB5EW8X45B6X8FE [0m
[32mLoading Rule Module Order_Kafka_Integration 01JP732F0AF6ECED61ENW0PT21 [0m
[32mLoading Rule Module Customer_Name_Constraint 01JP732F0D701XE32B8SJNE0JR [0m
[32mLoading Rule Module Customer_Name_Constraint 01JP732F0GBQ2A9KWHVX5AGQNK [0m

The following rules have been loaded
Rule Bank[0xffffb2bb65a0] (loaded 2025-03-13 06:29:55.104823)
Mapped Class[Customer] rules:
  Constraint Function: None 
  Derive <class 'database.models.Customer'>.balance as Sum(Order.amount_total Where Rule.sum(derive=Customer.balance, as_sum_of=Order.amount_total, where=lambda row: row.date_shipped is None) - <function init_rule.<locals>.<lambda> at 0xffffb161e8e0>)
  Constraint Function: None 
  Constraint Function: None 
  Constraint Function: None 
Mapped Class[Order] rules:
  Derive <class 'database.models.Order'>.amount_total as Sum(Item.amount Where  - None)
  RowEvent Order.send_row_to_kafka() 
Mapped Class[Item] rules:
  Derive <class 'database.models.Item'>.amount as Formula (-1): Rule.formula(derive=Item.amount, as_expression=la [...]
  Derive <class 'database.models.Item'>.unit_price as Copy(product.unit_price)

The following attributes have been referenced

..Customer.balance: constraint
..Customer.credit_limit: constraint
..Customer.balance: aggregate derivation
..Order.date_shipped: aggregate where clause
..Order.amount_total: sum derived from
..Customer.balance: constraint
..Customer.credit_limit: constraint
..Customer.name: constraint
..Customer.name: constraint
..Order.amount_total: aggregate derivation
..Item.amount: sum derived from
..Item.quantity: - formula
..Item.unit_price: - formula
..Item.unit_price: parent copy derivation
..Product.unit_price: parent copy from

The following rules have been activated
Rule Bank[0xffffb2bb65a0] (loaded 2025-03-13 06:29:55.104823)
Mapped Class[Customer] rules:
  Constraint Function: None 
  Derive <class 'database.models.Customer'>.balance as Sum(Order.amount_total Where Rule.sum(derive=Customer.balance, as_sum_of=Order.amount_total, where=lambda row: row.date_shipped is None) - <function init_rule.<locals>.<lambda> at 0xffffb161e8e0>)
  Constraint Function: None 
  Constraint Function: None 
  Constraint Function: None 
Mapped Class[Order] rules:
  Derive <class 'database.models.Order'>.amount_total as Sum(Item.amount Where  - None)
  RowEvent Order.send_row_to_kafka() 
Mapped Class[Item] rules:
  Derive <class 'database.models.Item'>.amount as Formula (1): Rule.formula(derive=Item.amount, as_expression=la [...]
  Derive <class 'database.models.Item'>.unit_price as Copy(product.unit_price)
Logic Bank 01.20.26 - 13 rules loaded
Exposing /Customer
Exposing /Item
Exposing /Order
Exposing /OrderDetail
Exposing /Product
Declare   API - api/expose_api_models, endpoint for each table on localhost:8282, customizing...
..discovered services: ['ontimize_api.py', 'system.py', 'new_service.py', 'newer_service.py']
Kafka Consumer not activated

API Logic Project loaded (not WSGI), version: 14.03.15
.. startup message: normal start
 (running from docker container at flask_host: 0.0.0.0 - may require refresh)

API Logic Project (name: 01JP732DJNM0EKQXAF2KA7VKKB) starting:
..Explore data and API at http_scheme://swagger_host:port http://localhost:6004   *
.... with flask_host: 0.0.0.0
.... and  swagger_port: 8282

Alert: These following are **Critical** to unlocking value for project: 01JP732DJNM0EKQXAF2KA7VKKB:
.. see logic.declare_logic.py       -- 
.. see security.declare_security.py -- ALERT:  *** Security Not Enabled ***


*************************************************************************
*   Startup Instructions: Open your Browser at: http://localhost:6004   *
*************************************************************************

 * Debugger is active!
 * Debugger PIN: 166-224-166
127.0.0.1 - - [13/Mar/2025 06:30:03] "GET /ui/admin/admin.yaml?v=1741847403629 HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:30:03] "GET /ui/admin/admin.yaml?v=1741847403927 HTTP/1.0" 200 -
Can't get count for <class 'database.spa_models.spa_page.SPAPage'> ((sqlite3.OperationalError) no such table: spa_pages
[SQL: SELECT count(*) AS count_1 
FROM (SELECT spa_pages.id AS spa_pages_id, spa_pages.name AS spa_pages_name, spa_pages.contact AS spa_pages_contact 
FROM spa_pages) AS anon_1]
(Background on this error at: https://sqlalche.me/e/20/e3q8))
Generic Error: (sqlite3.OperationalError) no such table: spa_pages
[SQL: SELECT spa_pages.id AS spa_pages_id, spa_pages.name AS spa_pages_name, spa_pages.contact AS spa_pages_contact 
FROM spa_pages ORDER BY spa_pages.name
 LIMIT ? OFFSET ?]
[parameters: (10, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Error in http://localhost/01JP732DJNM0EKQXAF2KA7VKKB/SPAPage?include=SectionList&page[limit]=10&page[number]=1&page[offset]=0&page[size]=10&sort=name
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: spa_pages

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/safrs/jsonapi_formatting.py", line 201, in paginate
    instances = res_query.all()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2692, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2232, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2127, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1987, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: spa_pages
[SQL: SELECT spa_pages.id AS spa_pages_id, spa_pages.name AS spa_pages_name, spa_pages.contact AS spa_pages_contact 
FROM spa_pages ORDER BY spa_pages.name
 LIMIT ? OFFSET ?]
[parameters: (10, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)


Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: spa_pages

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/safrs/jsonapi_formatting.py", line 201, in paginate
    instances = res_query.all()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2692, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2232, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2127, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1987, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1968, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: spa_pages
[SQL: SELECT spa_pages.id AS spa_pages_id, spa_pages.name AS spa_pages_name, spa_pages.contact AS spa_pages_contact 
FROM spa_pages ORDER BY spa_pages.name
 LIMIT ? OFFSET ?]
[parameters: (10, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/safrs/safrs_api.py", line 674, in method_wrapper
    result = fun(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/safrs/jsonapi.py", line 277, in get
    links, data, count = paginate(instances, self.SAFRSObject)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/safrs/jsonapi_formatting.py", line 216, in paginate
    raise GenericError(f"{exc}")
safrs.errors.GenericError
Exception on /01JP732DJNM0EKQXAF2KA7VKKB/SPAPage [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask_restful_swagger_2/__init__.py", line 39, in decorator
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask_restful_swagger_2/swagger.py", line 219, in inner
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/safrs/safrs_api.py", line 708, in method_wrapper
    abort(status_code, errors=[errors])
  File "/usr/local/lib/python3.12/site-packages/flask_restful/__init__.py", line 32, in abort
    original_flask_abort(http_status_code)
  File "/usr/local/lib/python3.12/site-packages/flask/helpers.py", line 277, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/werkzeug/exceptions.py", line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
127.0.0.1 - - [13/Mar/2025 06:30:03] "[35m[1mGET /01JP732DJNM0EKQXAF2KA7VKKB/SPAPage?include=SectionList&page[limit]=10&page[number]=1&page[offset]=0&page[size]=10&sort=name HTTP/1.0[0m" 500 -
127.0.0.1 - - [13/Mar/2025 06:30:04] "GET /ui/admin/admin.yaml?v=1741847404199 HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:30:06] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Customer?include=&page[limit]=25&page[number]=1&page[offset]=0&page[size]=25&sort=-id HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:30:06] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Customer?include=&page[limit]=25&page[number]=1&page[offset]=0&page[size]=25&sort=name HTTP/1.0" 200 -

Logic Phase:		ROW LOGIC		(session=0xffffb0060b00) (sqlalchemy before_flush)			
..Customer[None] {Insert - client} id: None, name: x, balance: None, credit_limit: None  row: 0xffffabf50380  session: 0xffffb0060b00  ins_upd_dlt: ins, initial: ins
..Customer[None] {server aggregate_defaults: balance } id: None, name: x, balance: 0, credit_limit: None  row: 0xffffabf50380  session: 0xffffb0060b00  ins_upd_dlt: ins, initial: ins
..Customer[None] {server all_defaults: credit_limit } id: None, name: x, balance: 0, credit_limit: 0  row: 0xffffabf50380  session: 0xffffb0060b00  ins_upd_dlt: ins, initial: ins
Logic Phase:		COMMIT LOGIC		(session=0xffffb0060b00)   										
Logic Phase:		AFTER_FLUSH LOGIC	(session=0xffffb0060b00)   										

These Rules Fired (see Logic Phases, above, for actual order):		##

Logic Phase:		COMPLETE(session=0xffffb0060b00))       	
127.0.0.1 - - [13/Mar/2025 06:30:12] "[35m[1mPOST /01JP732DJNM0EKQXAF2KA7VKKB/Customer HTTP/1.0[0m" 201 -
127.0.0.1 - - [13/Mar/2025 06:30:12] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Order?filter[customer_id]=5&page[limit]=25&page[offset]=0&sort=-id&include=ItemList,OrderDetailList,customer,ItemList,OrderDetailList,customer HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:30:12] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Customer/5?include=OrderList,OrderList&page[limit]=2 HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:30:12] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Customer/5?include=OrderList,OrderList&page[limit]=2 HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:31:17] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Customer?include=&page[limit]=25&page[number]=1&page[offset]=0&page[size]=25&sort=-id HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:31:17] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Customer?include=&page[limit]=25&page[number]=1&page[offset]=0&page[size]=25&sort=name HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:31:20] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Customer/1?include=OrderList,OrderList&page[limit]=2 HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:31:20] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Customer/1?include=OrderList,OrderList&page[limit]=2 HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:31:20] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Order?filter[customer_id]=1&page[limit]=25&page[offset]=0&sort=-id&include=ItemList,OrderDetailList,customer,ItemList,OrderDetailList,customer HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:31:23] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Customer/1?include=OrderList,OrderList&page[limit]=2 HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:31:23] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Order/1?include=ItemList,OrderDetailList,customer,ItemList,OrderDetailList,customer&page[limit]=2 HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:31:23] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Order/1?include=ItemList,OrderDetailList,customer,ItemList,OrderDetailList,customer&page[limit]=2 HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:31:23] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Customer/1?include=OrderList,OrderList&page[limit]=2 HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:31:23] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Item?filter[order_id]=1&page[limit]=25&page[offset]=0&sort=-id&include=OrderDetailList,order,product,OrderDetailList,order,product HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:31:23] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Order/1?include=ItemList,OrderDetailList,customer,ItemList,OrderDetailList,customer&page[limit]=2 HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:31:23] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Customer/1?include=OrderList,OrderList&page[limit]=2 HTTP/1.0" 200 -
Not found: Invalid "Product" ID "2"
127.0.0.1 - - [13/Mar/2025 06:31:23] "[33mGET /01JP732DJNM0EKQXAF2KA7VKKB/Product/2?include=ItemList,ItemList&page[limit]=2 HTTP/1.0[0m" 404 -
Not found: Invalid "Product" ID "1"
127.0.0.1 - - [13/Mar/2025 06:31:23] "[33mGET /01JP732DJNM0EKQXAF2KA7VKKB/Product/1?include=ItemList,ItemList&page[limit]=2 HTTP/1.0[0m" 404 -
127.0.0.1 - - [13/Mar/2025 06:31:27] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Product?include=&page[limit]=25&page[number]=1&page[offset]=0&page[size]=25&sort=-id HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:31:27] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Order?include=customer,customer&page[limit]=25&page[number]=1&page[offset]=0&page[size]=25&sort=-id HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:31:27] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Product?filter[id]=2&include=&page[limit]=10&page[number]=1&page[offset]=0&page[size]=10&sort=name HTTP/1.0" 200 -
127.0.0.1 - - [13/Mar/2025 06:31:27] "GET /01JP732DJNM0EKQXAF2KA7VKKB/Order?filter[id]=1&include=customer,customer&page[limit]=10&page[number]=1&page[offset]=0&page[size]=10&sort=id HTTP/1.0" 200 -

Logic Phase:		ROW LOGIC		(session=0xffffabfe8ef0) (sqlalchemy before_flush)			
..Item[2] {Update - client} id: 2, order_id: 1, product_id: 2, quantity:  [5-->] 5555, unit_price: 20, amount: 100  row: 0xffffabfeb980  session: 0xffffabfe8ef0  ins_upd_dlt: upd, initial: upd
..Item[2] {Formula amount} id: 2, order_id: 1, product_id: 2, quantity:  [5-->] 5555, unit_price: 20, amount:  [100-->] 111100  row: 0xffffabfeb980  session: 0xffffabfe8ef0  ins_upd_dlt: upd, initial: upd
....Order[1] {Update - Adjusting order: amount_total} id: 1, customer_id: 1, amount_total:  [200.0000000000-->] 111200.0000000000, date_shipped: None, notes: Urgent  row: 0xffffab530650  session: 0xffffabfe8ef0  ins_upd_dlt: upd, initial: upd
......Customer[1] {Update - Adjusting customer: balance} id: 1, name: Alice, balance:  [500.0000000000-->] 111500.0000000000, credit_limit: 1000.0000000000  row: 0xffffab530890  session: 0xffffabfe8ef0  ins_upd_dlt: upd, initial: upd
......Customer[1] {Constraint Failure: Customer balance (111500.0000000000) exceeds credit limit (1000.0000000000)} id: 1, name: Alice, balance:  [500.0000000000-->] 111500.0000000000, credit_limit: 1000.0000000000  row: 0xffffab530890  session: 0xffffabfe8ef0  ins_upd_dlt: upd, initial: upd

These Rules Fired (see Logic Phases, above, for actual order):		##
  Customer		##
    1. Constraint Function: None 		##
    2. Derive <class 'database.models.Customer'>.balance as Sum(Order.amount_total Where Rule.sum(derive=Customer.balance, as_sum_of=Order.amount_total, where=lambda row: row.date_shipped is None) - <function init_rule.<locals>.<lambda> at 0xffffb161e8e0>)		##
  Item		##
    3. Derive <class 'database.models.Item'>.amount as Formula (1): Rule.formula(derive=Item.amount, as_expression=la [...]		##
  Order		##
    4. Derive <class 'database.models.Order'>.amount_total as Sum(Item.amount Where  - None)		##

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/safrs/safrs_api.py", line 674, in method_wrapper
    result = fun(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/safrs/jsonapi.py", line 324, in patch
    instance = self._patch_instance(data, id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/safrs/jsonapi.py", line 360, in _patch_instance
    instance._s_patch(**attributes)
  File "/usr/local/lib/python3.12/site-packages/safrs/base.py", line 485, in _s_patch
    safrs.DB.session.commit()
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/scoping.py", line 553, in commit
    return self._proxied.commit()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1906, in commit
    trans.commit(_to_root=True)
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1221, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1196, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4154, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4183, in _flush
    self.dispatch.before_flush(self, flush_context, objects)
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/event/attr.py", line 378, in __call__
    fn(*args, **kw)
  File "/usr/local/lib/python3.12/site-packages/logic_bank/exec_trans_logic/listeners.py", line 65, in before_flush
    logic_row.update(reason="client")
  File "/usr/local/lib/python3.12/site-packages/logic_bank/exec_row_logic/logic_row.py", line 1250, in update
    self._adjust_parent_aggregates()  # parent chaining (sum / count adjustments)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/logic_bank/exec_row_logic/logic_row.py", line 1189, in _adjust_parent_aggregates
    parent_adjuster.save_altered_parents(do_not_adjust_list=do_not_adjust_list)  # iff req'd (altered only)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/logic_bank/exec_row_logic/logic_row.py", line 1407, in save_altered_parents
    parent_logic_row.update(
  File "/usr/local/lib/python3.12/site-packages/logic_bank/exec_row_logic/logic_row.py", line 1250, in update
    self._adjust_parent_aggregates()  # parent chaining (sum / count adjustments)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/logic_bank/exec_row_logic/logic_row.py", line 1189, in _adjust_parent_aggregates
    parent_adjuster.save_altered_parents(do_not_adjust_list=do_not_adjust_list)  # iff req'd (altered only)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/logic_bank/exec_row_logic/logic_row.py", line 1407, in save_altered_parents
    parent_logic_row.update(
  File "/usr/local/lib/python3.12/site-packages/logic_bank/exec_row_logic/logic_row.py", line 1251, in update
    self._constraints()
  File "/usr/local/lib/python3.12/site-packages/logic_bank/exec_row_logic/logic_row.py", line 795, in _constraints
    each_constraint.execute(self)
  File "/usr/local/lib/python3.12/site-packages/logic_bank/rule_type/constraint.py", line 87, in execute
    ll.constraint_event(message=msg, logic_row=logic_row, constraint=self)
  File "/opt/projects/by-ulid/01JP732DJNM0EKQXAF2KA7VKKB/config/server_setup.py", line 282, in constraint_handler
    raise ValidationErrorExt(message=message, detail=detail)
config.server_setup.ValidationErrorExt
127.0.0.1 - - [13/Mar/2025 06:31:31] "[31m[1mPATCH /01JP732DJNM0EKQXAF2KA7VKKB/Item/2 HTTP/1.0[0m" 400 -
